### ISSUE TITLE
Add a versioning system for Ruby version

### ISSUE THREAD

**Issue by xredo** [MarsBased/circleci#1]
The Dockerfile defines the Ruby 2.4.1 version.  We need to create different tags for different Ruby versions. The master version will be the latest Ruby stable release.

**Comment by artero** [comment]
Done We have a branch for each version that we use and a tag for that versions, now we have the branches/versions:

- master/least (the most recent, currently 2.5.1) 
- ruby-2.5.1
- ruby-2.4.1
